name: terraform Deployment

on: 
  push:
    branches:
      - main

jobs: 
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    - name: set up terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.0

    - name: aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-west-2
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform
      
    - name: Terraform plan
      run: terraform plan 
      working-directory: ./terraform
      
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform


      
  
      
      
