name: Comprehensive GitHub Actions Workflow
on:
 # 1. Branch pattern for push
 push:
   # Trigger on push to main, develop, and feature branches
   branches:
     - main
     - develop
     - 'feature/**'
 # 2. Event with specific type
 issues:
   types:
     - opened
     - reopened
     - edited
 # 3. Multiple branches for pull request
 pull_request:
   branches:
     - main
     - develop
     - 'release/**'
