name: "Custom Triggers Workflow"
on:
 
 push:
   branches:
     - 'feature/*' # Matches branches like 'feature/xyz'
     - 'release/**' # Matches branches like 'release/v1.0.0'

 issues:
   types:
     - opened # Trigger when an issue is opened
     - reopened # Trigger when an issue is reopened

 pull_request:
   branches:
     - 'main'
     - 'develop'
     - 'hotfix/*' # Matches branches like 'hotfix/fix-xyz'

 push:
   paths:
     - 'src/**' # Any changes under the src directory
     - 'docs/**' # Any changes under the docs directory
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v3
     - name: Display event details
       run: echo "Triggered by ${{ github.event_name }} on branch ${{ github.ref_name }}"
